### ISSUE TITLE
Question about how to manual annotate the ground truth mask with SAM2

### ISSUE THREAD

**Issue by aopolin-lv** [luccachiang/robots-pretrain-robots#6]
Hello, it is a nice work. Especially, it measures the relationship between visual representations learned in existing manipulation models. I am curious about how can I get the ground truth of mask with SAM2 refered in Section 3 `The ground truth is generated using the powerful video segmentation model SAM2 (Ravi et al., 2024), with manual annotation of key points within the target regions.` I will appreciate it if you give an example.

**Comment by luccachiang** [comment]
Sure! I recommend you to use [this GUI](https://github.com/YunxuanMao/SAM2-GUI). Just follow the installation and usage, and you can do the video segmentation. It is better than the meta demo online since the official web UI will carry watermarks and change the number of video frames. If you have any problems while using the GUI, please feel free to comment in this issue. Note that you may need a workstation with a monitor. Headless servers may not be supported :)
